project_id = "xpmclamtmlogogcpogbq"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.app"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_refresh_token_reuse_interval = 10
enable_signup = true
enable_email_confirmations = false

[db]
port = 54322

[edge_runtime]
enabled = true
port = 54323

[functions.n8n-submit-draft]
verify_jwt = false

[functions.send-whatsapp-notification]
verify_jwt = false

[supabase]
host = "localhost"
port = 54321